apiVersion: apps/v1
kind: Deployment
metadata:
  name: overprovisioned-api
  namespace: kubefit-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: overprovisioned-api
  template:
    metadata:
      labels:
        app: overprovisioned-api
    spec:
      containers:
        - name: api
          image: nginx:1.29-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "40m"
              memory: "48Mi"
